spec:
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: ELASTICSEARCH_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: ELASTICSEARCH_HOST
        - name: ELASTICSEARCH_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: ELASTICSEARCH_PORT