apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-gitops-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FevziVila/SemITPM.git  
    targetRevision: HEAD
    path: deployments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true