apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: gitops-demo
  labels:
    app: frontend
    environment: dev
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: NodePort