apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: gitops-demo
  labels:
    app: backend
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: feivel123/gitops-backend:latest
        ports:
        - containerPort: 8080